server:
  port: 8088
spring:
  application:
    name: project-management-mybatis-app
  pid:
    file: ${spring.application.name}.pid
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus_example?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 1234
    hikari:
      connection-timeout: 30000
      minimum-idle: 10
      connection-test-query: SELECT 1
      maximum-pool-size: 50
      auto-commit: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: me.project.management.entity
logging:
  level:
    me.project.management: debug
  file:
    name: ${spring.application.name}.log
swagger:
  enabled: true
  version: 1.1.0
  title: Project Management
  base-package: me.project.management.controller
  exclude-path: /ops/**, /error
  base-path: /**
  description: Project Management details
