server:
  port: 8080
spring:
  application:
    name: project-management-mybatis-app
  pid:
    file: ${spring.application.name}.pid
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pm_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: me.project.management.entity
logging:
  level:
    me.project.management: debug
  file:
    name: ${spring.application.name}.log
jwt:
  secret: techgeeknext
swagger:
  enabled: true
  version: 1.1.0
  title: Project Management
  base-package: me.project.management.controller
  exclude-path: /ops/**, /error
  base-path: /**
  description: Project Management details
